# Setup
title:               Dan's Blog
tagline:             'DevOps and such'
description:         'add something'
url:                 https://dme86.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dan 'dme' Meier
  url:
  email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
excerpt_separator: <!-- more -->
